### ISSUE TITLE
[Feature] NetworkPolicy in helm chart

### ISSUE THREAD

**Issue by jcpunk** [postfinance/kubelet-csr-approver#158]
It would be handy if the helm chart contained an optional network policy to restrict what this container can access over the network.

**Comment by clementnuss** [comment]
hi @jcpunk 

I had a quick look, and I am not too sure what the network policy should look like.

it seems whitelisting the apiserver for egress traffic isn't as simple as expected: https://github.com/cilium/cilium/issues/20550

(seems to require specifying the CIDR of the API server IP)

I've also checked another controller (OPA Gatekeeper) to see how they do it: 
https://github.com/open-policy-agent/gatekeeper/blob/b7230e0bdc3479b867acd2fd0d7192b1182c59d4/charts/gatekeeper/templates/gatekeeper-controller-manager-network-policy.yaml#L4

they only have an optional NetPol that restricts what can enter the pod, nothing for egress.

How would you see it in our case ?

**Comment by jcpunk** [comment]
Alas, I don't know enough about what it needs networking wise...

perhaps something like:
```yaml
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
    - port: 443
      protocol: TCP
```
